from Question import Question


class Answer:
    """
    This Object will be generated by connecting server based on the json sent in by frontend
    This Object will be sent to DNA
    DNA will return a Question Object & A list of data
    """

    question = Question()
    """Associated question object"""
    answers = []
    """
    answer part
    """

    def __init__(self):
        self.question = Question()


    def parsejson(self,immutableDict):
        """
        This method parse json from the frontend team
        :param: a string in json format
        :return: None
        """
        self.answers = immutableDict.getlist(self.question.id)






